name: assesment_teklogue
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  flutter_otp_text_field: ^1.1.1
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.4
  logger: ^2.0.2+1
  meta: ^1.10.0
  currency_formatter: ^2.2.1
  extended_masked_text: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
